### ISSUE TITLE
Login -page HTML:ksi

### ISSUE THREAD

**Issue by jannegylling** [qlma/qlma.github.io#5]
Login -sivu pitäisi vääntää html:ksi

![login](https://cloud.githubusercontent.com/assets/3054429/9560988/9a90a1f4-4e3b-11e5-9c08-c51585e32dcf.jpg)

**Comment by jannegylling** [comment]
Tässä PSD

https://dl.dropboxusercontent.com/u/33946169/login.psd

**Comment by tuomas-tk** [comment]
Tuossa ois vähän pohjaa:
https://www.dropbox.com/s/28nah4ahascfvt0/qlmalogin.zip?dl=0

Taustaa en saanut toimimaan kunnolla, ja mobiilissa näyttää vielä vähän oudolta.

**Comment by woltage** [comment]
Ooh, kiitti Tuomas! Pitäiskös toi heittää versionhallintaan? 

Jos laittas server projektin alle /layouts hakemistoon. Jos viittit Tuomas laittaa niin sun nimi jää lähdekoodeihin näkyviin eikä mun :)

Jos et osaa tehdä Pull Requestia niin huikkaa käydään yhdessä läpi miten tehdään.

**Comment by woltage** [comment]
Tuomas vei koodit server projektin alle
